Update 02raw.yml

diff --git a/.github/workflows/02raw.yml b/.github/workflows/02raw.yml
--- a/.github/workflows/02raw.yml
+++ b/.github/workflows/02raw.yml
@@ -48,8 +48,8 @@ jobs:
         GO_FOLDER_TEMP: ${{ secrets.GO_FOLDER_TEMP }}
         FOLDER: "DL"
       run: |
-        go-ul ftp -d 'DL/' -r -u '${{ env.FTP_1F }}' -O
-        pip install requests
+        echo "1F... " && { go-ul ftp -d 'DL/' -r -u '${{ env.FTP_1F }}' -O > /dev/null 2>&1 && echo "success" || echo "fail"; }
+        pip install --quiet requests
         python 5file-ul.py
         go-ul catbox -d 'DL/' -r -o 'output/link.txt'
         mv 'output/link.txt' "output/$(echo $(date +'[%Y-%m-%d]')) ${{github.event.inputs.filename}}.txt"
